export default {
  login: "octavianusfian",
  id: 73276407,
  node_id: "MDQ6VXNlcjczMjc2NDA3",
  avatar_url: "https://avatars.githubusercontent.com/u/73276407?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/octavianusfian",
  html_url: "https://github.com/octavianusfian",
  followers_url: "https://api.github.com/users/octavianusfian/followers",
  following_url:
    "https://api.github.com/users/octavianusfian/following{/other_user}",
  gists_url: "https://api.github.com/users/octavianusfian/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/octavianusfian/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/octavianusfian/subscriptions",
  organizations_url: "https://api.github.com/users/octavianusfian/orgs",
  repos_url: "https://api.github.com/users/octavianusfian/repos",
  events_url: "https://api.github.com/users/octavianusfian/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/octavianusfian/received_events",
  type: "User",
  user_view_type: "public",
  site_admin: false,
  name: "octavianus fian",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "hello",
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 7,
  following: 5,
  created_at: "2020-10-22T07:25:15Z",
  updated_at: "2025-03-15T16:42:08Z",
};
