export default [
  {
    login: "tonic-6101",
    id: 43235418,
    node_id: "MDQ6VXNlcjQzMjM1NDE4",
    avatar_url: "https://avatars.githubusercontent.com/u/43235418?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tonic-6101",
    html_url: "https://github.com/tonic-6101",
    followers_url: "https://api.github.com/users/tonic-6101/followers",
    following_url:
      "https://api.github.com/users/tonic-6101/following{/other_user}",
    gists_url: "https://api.github.com/users/tonic-6101/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/tonic-6101/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tonic-6101/subscriptions",
    organizations_url: "https://api.github.com/users/tonic-6101/orgs",
    repos_url: "https://api.github.com/users/tonic-6101/repos",
    events_url: "https://api.github.com/users/tonic-6101/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/tonic-6101/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
  {
    login: "danilhendrasr",
    id: 45989466,
    node_id: "MDQ6VXNlcjQ1OTg5NDY2",
    avatar_url: "https://avatars.githubusercontent.com/u/45989466?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/danilhendrasr",
    html_url: "https://github.com/danilhendrasr",
    followers_url: "https://api.github.com/users/danilhendrasr/followers",
    following_url:
      "https://api.github.com/users/danilhendrasr/following{/other_user}",
    gists_url: "https://api.github.com/users/danilhendrasr/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/danilhendrasr/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/danilhendrasr/subscriptions",
    organizations_url: "https://api.github.com/users/danilhendrasr/orgs",
    repos_url: "https://api.github.com/users/danilhendrasr/repos",
    events_url: "https://api.github.com/users/danilhendrasr/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/danilhendrasr/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
  {
    login: "arryaaas",
    id: 52322895,
    node_id: "MDQ6VXNlcjUyMzIyODk1",
    avatar_url: "https://avatars.githubusercontent.com/u/52322895?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/arryaaas",
    html_url: "https://github.com/arryaaas",
    followers_url: "https://api.github.com/users/arryaaas/followers",
    following_url:
      "https://api.github.com/users/arryaaas/following{/other_user}",
    gists_url: "https://api.github.com/users/arryaaas/gists{/gist_id}",
    starred_url: "https://api.github.com/users/arryaaas/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/arryaaas/subscriptions",
    organizations_url: "https://api.github.com/users/arryaaas/orgs",
    repos_url: "https://api.github.com/users/arryaaas/repos",
    events_url: "https://api.github.com/users/arryaaas/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/arryaaas/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
  {
    login: "PandeYogam",
    id: 54659358,
    node_id: "MDQ6VXNlcjU0NjU5MzU4",
    avatar_url: "https://avatars.githubusercontent.com/u/54659358?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/PandeYogam",
    html_url: "https://github.com/PandeYogam",
    followers_url: "https://api.github.com/users/PandeYogam/followers",
    following_url:
      "https://api.github.com/users/PandeYogam/following{/other_user}",
    gists_url: "https://api.github.com/users/PandeYogam/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/PandeYogam/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/PandeYogam/subscriptions",
    organizations_url: "https://api.github.com/users/PandeYogam/orgs",
    repos_url: "https://api.github.com/users/PandeYogam/repos",
    events_url: "https://api.github.com/users/PandeYogam/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/PandeYogam/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
  {
    login: "Alstonargodi",
    id: 55945729,
    node_id: "MDQ6VXNlcjU1OTQ1NzI5",
    avatar_url: "https://avatars.githubusercontent.com/u/55945729?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Alstonargodi",
    html_url: "https://github.com/Alstonargodi",
    followers_url: "https://api.github.com/users/Alstonargodi/followers",
    following_url:
      "https://api.github.com/users/Alstonargodi/following{/other_user}",
    gists_url: "https://api.github.com/users/Alstonargodi/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Alstonargodi/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Alstonargodi/subscriptions",
    organizations_url: "https://api.github.com/users/Alstonargodi/orgs",
    repos_url: "https://api.github.com/users/Alstonargodi/repos",
    events_url: "https://api.github.com/users/Alstonargodi/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Alstonargodi/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
  {
    login: "thisham",
    id: 59078748,
    node_id: "MDQ6VXNlcjU5MDc4NzQ4",
    avatar_url: "https://avatars.githubusercontent.com/u/59078748?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/thisham",
    html_url: "https://github.com/thisham",
    followers_url: "https://api.github.com/users/thisham/followers",
    following_url:
      "https://api.github.com/users/thisham/following{/other_user}",
    gists_url: "https://api.github.com/users/thisham/gists{/gist_id}",
    starred_url: "https://api.github.com/users/thisham/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/thisham/subscriptions",
    organizations_url: "https://api.github.com/users/thisham/orgs",
    repos_url: "https://api.github.com/users/thisham/repos",
    events_url: "https://api.github.com/users/thisham/events{/privacy}",
    received_events_url: "https://api.github.com/users/thisham/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
  {
    login: "yuneda",
    id: 62292790,
    node_id: "MDQ6VXNlcjYyMjkyNzkw",
    avatar_url: "https://avatars.githubusercontent.com/u/62292790?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/yuneda",
    html_url: "https://github.com/yuneda",
    followers_url: "https://api.github.com/users/yuneda/followers",
    following_url: "https://api.github.com/users/yuneda/following{/other_user}",
    gists_url: "https://api.github.com/users/yuneda/gists{/gist_id}",
    starred_url: "https://api.github.com/users/yuneda/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/yuneda/subscriptions",
    organizations_url: "https://api.github.com/users/yuneda/orgs",
    repos_url: "https://api.github.com/users/yuneda/repos",
    events_url: "https://api.github.com/users/yuneda/events{/privacy}",
    received_events_url: "https://api.github.com/users/yuneda/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
];
